// <auto-generated />
namespace WebApiWitnPostgreSQL.DataContexts.StoreMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIdAutoGenerationToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIdAutoGenerationToBook));
        
        string IMigrationMetadata.Id
        {
            get { return "201603291151566_AddIdAutoGenerationToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
